# Copyright (c) 2022-2025, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

params:
  seed: 42

  # environment wrapper clipping
  env:
    clip_actions: 1.0

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None

        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [256, 128, 64]
      activation: elu
      d2rl: False

      initializer:
        name: default
      regularizer:
        name: None

  load_checkpoint: False # flag which sets whether to load the checkpoint
  load_path: '' # path to the checkpoint to load

  config:
    name: franka_slide_state_direct
    env_name: rlgpu
    device: 'cuda:0'
    device_name: 'cuda:0'
    multi_gpu: False
    ppo: True
    mixed_precision: False
    normalize_input: True
    normalize_value: True
    # value_bootstrap: True
    num_actors: -1  # configured from the script (based on num_envs)
    reward_shaper:
      scale_value: 0.01

    normalize_advantage: True
    gamma: 0.99
    tau: 0.95

    # 1) Make learning rate more robust, less tightly KL-gated
    learning_rate: 3e-4          # was 5e-4, fine-tuned but not huge
    lr_schedule: fixed           # avoid aggressive LR shrinking early

    # 2) Loosen the KL constraint a bit
    kl_threshold: 0.02           # was 0.01 / 0.008; gives more room to move

    # 3) Encourage more exploration
    entropy_coef: 0.01           # was 0.003 (and you tried 0.0)

    score_to_win: 100000000
    max_epochs: 5000 #1500
    save_best_after: 200
    save_frequency: 100
    grad_norm: 1.0

    # 4) Keep PPO clipping but reduce overfitting per batch
    e_clip: 0.2
    horizon_length: 16
    minibatch_size: 4096         # was 8192; more frequent updates
    mini_epochs: 4               # was 8; less overfitting to early policy

    critic_coef: 4
    clip_value: True
    seq_length: 4
    bounds_loss_coef: 0.0001
